### ISSUE TITLE
pload times out when uploading playlist for prerecorded show

### ISSUE THREAD

**Issue by echarlie** [wuvt/pload#22]
e.g. I try to upload a 94-line playlist, and I assume in the process of checking all of the tracks, I get a timeout error. the playlist was still uploaded completely.

**Comment by mutantmonkey** [comment]
Yeah, sounds like validation is timing out. We'll probably either want to do that asynchronously or increase the nginx timeout or uWSGI harakiri option.

**Comment by mutantmonkey** [comment]
We could potentially remove the separate upload UI and have an "import M3U" option directly in the playlist editor with file processing on the client side. This will allow us to avoid timeouts caused by having to process too many tracks in a single request and remove the upload UI which the create functionality mostly duplicates.

**Comment by mutantmonkey** [comment]
I discussed this with @JasonDavidoff85 and it sounds like the timeout is happening at the auth proxy layer and the underlying request is still going through. We can increase the timeout for SSO (from the default of 10 seconds) which should fix this issue.

**Comment by mutantmonkey** [comment]
I'm going to reopen this for now until we're sure the issue is resolved, even though recent changes may have helped here. I also increased the upstream timeout to 30s in the SSO config.

**Comment by mutantmonkey** [comment]
I haven't heard any more reports of this happening. I think it should be safe to close this.
