### ISSUE TITLE
"import m3u" flows weirdly on narrower screens

### ISSUE THREAD

**Issue by echarlie** [wuvt/pload#35]
see:

![2020-07-19-123414_7600x1440_scrot](https://user-images.githubusercontent.com/18043413/87880044-7f992900-c9bc-11ea-80c8-cd356e8b805c.png)

I also don't think it should be next to the "add link" button, but that's just me.

**Comment by mutantmonkey** [comment]
What resolution are you using? I'll do some testing using that.

I've been thinking about some ideas to redo the whole lower panel because I don't like that there are two text boxes visible at the same time. I'm wondering if we should just have the search visible by default with an Advanced dropdown next to it with buttons to add a track by URL and import M3U. The "add by URL" would pop open a modal similar to the "Import M3U" one. I'd like to collect some additional feedback though before moving forward with that.

As a sidenote, looks like we need to move that table outside of card-body so it fills the full width and "Length" doesn't wrap like it is in this screenshot.

**Comment by echarlie** [comment]
it should work (without switching to a mobile UI, or the proposed widescreen ui of #12 ) on screens of 1280x1024, because we have those in the station.
